name: CodeBattle Arena CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  # Essential checks
  quality-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Syntax validation
      run: |
        echo "🔍 Checking JavaScript syntax..."
        node -c server/index.js
        node -c server/database.js
        node -c server/arenaSocket.js
        echo "✅ Syntax check passed"
    
    - name: Server startup test
      run: |
        echo "🚀 Testing server startup..."
        timeout 10s npm start || echo "✅ Server startup test completed"
    
    - name: Code quality scan (non-blocking)
      run: npm run lint || echo "⚠️ Code style issues found - review recommended"
      continue-on-error: true

  # Deploy only on main branch
  deploy:
    runs-on: ubuntu-latest
    needs: quality-check
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}
    
    - name: Success notification
      run: |
        echo "🎉 CodeBattle Arena deployed successfully!"
        echo "🌐 Application should be live in 2-3 minutes"
        echo "📝 Commit: ${{ github.event.head_commit.message }}"
