name: Simple Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Quick syntax check
      run: node -c server/index.js
    
    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}
      if: github.ref == 'refs/heads/main'
    
    - name: Deployment notification
      run: |
        echo "🚀 CodeBattle Arena deployed successfully!"
        echo "📝 Commit: ${{ github.event.head_commit.message }}"
        echo "👤 Author: ${{ github.actor }}"
